export type ProduceUnit = 'kg' | 'each';
export type Confidence = 'ok' | 'verify';

export type ProduceRow = {
  id: number;
  category: 'Fruit' | 'Vegetables';
  product: string;
  wholesaleSource: string;
  wholesaleUnit: ProduceUnit;
  wholesalePrice: number;
  wholesaleQty: number;
  retailProduct: string;
  retailUnit: ProduceUnit;
  retailPrice: number;
  /** Only set when wholesale and retail units differ, or wholesale is sold "each" (needed to price freight per item). */
  avgWeightG: number | null;
  confidence: Confidence;
  note: string;
};

/**
 * Wholesale: Eco-Farms Brisbane availability list, w/c 24-26 Aug 2026 (doc/26_Aug_wholesale-eco-farms.xlsx).
 * Retail: Fresh Organic Merrimac price board, 23 Aug 2026 (doc/fresh_organic_merrimac_retailer_pricing_1.jpeg).
 * Fresh produce is GST-free in Australia, so no GST adjustment is applied anywhere here.
 */
export const PRODUCE_ROWS: ProduceRow[] = [
  // ---------- FRUIT ----------
  {
    id: 1,
    category: 'Fruit',
    product: 'Apples (Pink Lady)',
    wholesaleSource: '12kg box · McMahon',
    wholesaleUnit: 'kg',
    wholesalePrice: 90,
    wholesaleQty: 12,
    retailProduct: 'Apples loose',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'verify',
    note: "Board's price column position for 'apples loose' vs '2nds bags' is ambiguous in the photo — verify which price applies."
  },
  {
    id: 2,
    category: 'Fruit',
    product: 'Avocado (Hass)',
    wholesaleSource: '5.5kg tray · Avorama',
    wholesaleUnit: 'kg',
    wholesalePrice: 45,
    wholesaleQty: 5.5,
    retailProduct: 'Avocados Hass, each',
    retailUnit: 'each',
    retailPrice: 2.9,
    avgWeightG: 200,
    confidence: 'ok',
    note: 'Retail also offers 3-for-$8 (~$2.67 ea) — using the single-unit price.'
  },
  {
    id: 3,
    category: 'Fruit',
    product: 'Grapefruit (Yellow)',
    wholesaleSource: '15kg box · Riversdale',
    wholesaleUnit: 'kg',
    wholesalePrice: 42,
    wholesaleQty: 15,
    retailProduct: 'Grapefruit loose',
    retailUnit: 'kg',
    retailPrice: 6.9,
    avgWeightG: null,
    confidence: 'verify',
    note: "Wholesale is Yellow grapefruit; retail board doesn't state variety — may not be the same cultivar."
  },
  {
    id: 4,
    category: 'Fruit',
    product: 'Kiwifruit',
    wholesaleSource: '10kg box · Comboyne',
    wholesaleUnit: 'kg',
    wholesalePrice: 135,
    wholesaleQty: 10,
    retailProduct: 'Kiwifruit',
    retailUnit: 'kg',
    retailPrice: 4.9,
    avgWeightG: null,
    confidence: 'verify',
    note: 'This retail figure looks too low for organic kiwifruit (typically $10-16/kg) — likely a misread digit on the photo. Verify before trusting this row.'
  },
  {
    id: 5,
    category: 'Fruit',
    product: 'Lemons (1st grade)',
    wholesaleSource: '12-13kg box · Sunzest',
    wholesaleUnit: 'kg',
    wholesalePrice: 67,
    wholesaleQty: 12.5,
    retailProduct: 'Lemons 1st grade',
    retailUnit: 'kg',
    retailPrice: 6.9,
    avgWeightG: null,
    confidence: 'verify',
    note: 'Board shows a hand revision (11.90 struck through, 6.90 written) — confirm which price is current.'
  },
  {
    id: 6,
    category: 'Fruit',
    product: 'Limes',
    wholesaleSource: '5kg box · Stannary',
    wholesaleUnit: 'kg',
    wholesalePrice: 115,
    wholesaleQty: 5,
    retailProduct: 'Limes',
    retailUnit: 'kg',
    retailPrice: 29.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 7,
    category: 'Fruit',
    product: 'Mandarin (Daisy)',
    wholesaleSource: '9kg box · Karra',
    wholesaleUnit: 'kg',
    wholesalePrice: 62,
    wholesaleQty: 9,
    retailProduct: 'Mandarins Daisy',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 8,
    category: 'Fruit',
    product: 'Mandarin (Imperial)',
    wholesaleSource: '9kg box · Karra',
    wholesaleUnit: 'kg',
    wholesalePrice: 80,
    wholesaleQty: 9,
    retailProduct: 'Mandarins Imperial',
    retailUnit: 'kg',
    retailPrice: 12.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 9,
    category: 'Fruit',
    product: 'Oranges (Navel)',
    wholesaleSource: '15kg box · Sunzest',
    wholesaleUnit: 'kg',
    wholesalePrice: 56,
    wholesaleQty: 15,
    retailProduct: 'Oranges',
    retailUnit: 'kg',
    retailPrice: 7.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Retail variety not stated; wholesale list also has Navelina/Blood/Cara Cara at other prices.'
  },
  {
    id: 10,
    category: 'Fruit',
    product: 'Passionfruit',
    wholesaleSource: 'per kg · Lakeland',
    wholesaleUnit: 'kg',
    wholesalePrice: 14,
    wholesaleQty: 1,
    retailProduct: 'Passionfruit',
    retailUnit: 'kg',
    retailPrice: 19.9,
    avgWeightG: null,
    confidence: 'ok',
    note: "Wholesale marked 'extremely limited' stock this week."
  },
  {
    id: 11,
    category: 'Fruit',
    product: 'Papaya / Paw Paw',
    wholesaleSource: '6-7kg box · JAH Farming',
    wholesaleUnit: 'kg',
    wholesalePrice: 51,
    wholesaleQty: 6.5,
    retailProduct: 'Paw Paw',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Assumed papaya and paw paw are the same comparison here.'
  },
  {
    id: 12,
    category: 'Fruit',
    product: 'Pears (Packham)',
    wholesaleSource: '15kg box · GVIP',
    wholesaleUnit: 'kg',
    wholesalePrice: 80,
    wholesaleQty: 15,
    retailProduct: 'Pears',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Retail variety not stated (wholesale also has Beurre Bosc at $100/15kg).'
  },
  {
    id: 13,
    category: 'Fruit',
    product: 'Strawberries',
    wholesaleSource: '1 punnet · Coochin Hills',
    wholesaleUnit: 'each',
    wholesalePrice: 6.2,
    wholesaleQty: 1,
    retailProduct: 'Strawberries 250g',
    retailUnit: 'each',
    retailPrice: 8.9,
    avgWeightG: 250,
    confidence: 'ok',
    note: 'Assumes the wholesale punnet is also ~250g (not stated on the price list).'
  },
  {
    id: 14,
    category: 'Fruit',
    product: 'Tangelo',
    wholesaleSource: '9kg box · Karra',
    wholesaleUnit: 'kg',
    wholesalePrice: 60,
    wholesaleQty: 9,
    retailProduct: 'Tangelos',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 15,
    category: 'Fruit',
    product: 'Watermelon (mini seedless)',
    wholesaleSource: 'per kg · Organic Ag',
    wholesaleUnit: 'kg',
    wholesalePrice: 4,
    wholesaleQty: 1,
    retailProduct: 'Watermelon',
    retailUnit: 'kg',
    retailPrice: 5.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Retail variety not stated.'
  },

  // ---------- VEGETABLES ----------
  {
    id: 16,
    category: 'Vegetables',
    product: 'Beetroot',
    wholesaleSource: '10kg bag · Arahura/Busch',
    wholesaleUnit: 'kg',
    wholesalePrice: 28,
    wholesaleQty: 10,
    retailProduct: 'Beetroot loose',
    retailUnit: 'kg',
    retailPrice: 19.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Wholesale bag is field-run/unwashed; retail is market-ready — washing/trimming labour is not costed here.'
  },
  {
    id: 17,
    category: 'Vegetables',
    product: 'Broccoli',
    wholesaleSource: '8kg box · Mt Whitestone',
    wholesaleUnit: 'kg',
    wholesalePrice: 92,
    wholesaleQty: 8,
    retailProduct: 'Broccoli',
    retailUnit: 'kg',
    retailPrice: 4.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'A real result, not a misread — wholesale broccoli is running above retail this week.'
  },
  {
    id: 18,
    category: 'Vegetables',
    product: 'Broccolini',
    wholesaleSource: '12-bunch box (Baby Purple) · Peninsula',
    wholesaleUnit: 'each',
    wholesalePrice: 50,
    wholesaleQty: 12,
    retailProduct: 'Broccolini bunches',
    retailUnit: 'each',
    retailPrice: 16.9,
    avgWeightG: 120,
    confidence: 'verify',
    note: "Wholesale line is 'baby purple broccoli', not standard green broccolini — different product. Also unclear if $16.90 is per bunch or per kg."
  },
  {
    id: 19,
    category: 'Vegetables',
    product: 'Cabbage (green)',
    wholesaleSource: '1 each · Mt Whitestone',
    wholesaleUnit: 'each',
    wholesalePrice: 5.3,
    wholesaleQty: 1,
    retailProduct: 'Cabbages',
    retailUnit: 'each',
    retailPrice: 6.9,
    avgWeightG: 1200,
    confidence: 'ok',
    note: 'Retail also sells by the half ($4.50) or quarter ($2.90).'
  },
  {
    id: 20,
    category: 'Vegetables',
    product: 'Capsicum (green)',
    wholesaleSource: '5kg box · Isis River',
    wholesaleUnit: 'kg',
    wholesalePrice: 39,
    wholesaleQty: 5,
    retailProduct: 'Capsicum green',
    retailUnit: 'kg',
    retailPrice: 7.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'Wholesale line marked SPECIAL this week — normal price may be higher.'
  },
  {
    id: 21,
    category: 'Vegetables',
    product: 'Capsicum (red)',
    wholesaleSource: '5kg box · Moorland',
    wholesaleUnit: 'kg',
    wholesalePrice: 95,
    wholesaleQty: 5,
    retailProduct: 'Capsicum red',
    retailUnit: 'kg',
    retailPrice: 16.9,
    avgWeightG: null,
    confidence: 'ok',
    note: 'A real result — wholesale red capsicum currently costs more per kg than retail sells for.'
  },
  {
    id: 22,
    category: 'Vegetables',
    product: 'Carrots',
    wholesaleSource: '15kg box · Lockyer',
    wholesaleUnit: 'kg',
    wholesalePrice: 74,
    wholesaleQty: 15,
    retailProduct: 'Carrots loose',
    retailUnit: 'kg',
    retailPrice: 24.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 23,
    category: 'Vegetables',
    product: 'Cauliflower',
    wholesaleSource: '10 each · Mt Whitestone',
    wholesaleUnit: 'each',
    wholesalePrice: 47,
    wholesaleQty: 10,
    retailProduct: 'Cauliflower',
    retailUnit: 'each',
    retailPrice: 7.9,
    avgWeightG: 1500,
    confidence: 'ok',
    note: 'Retail also sells by the half ($4.50).'
  },
  {
    id: 24,
    category: 'Vegetables',
    product: 'Celery',
    wholesaleSource: '8 each · Black Crow/Bauer',
    wholesaleUnit: 'each',
    wholesalePrice: 40,
    wholesaleQty: 8,
    retailProduct: 'Celery',
    retailUnit: 'each',
    retailPrice: 7.9,
    avgWeightG: 600,
    confidence: 'ok',
    note: 'Retail also sells by the half ($4.50).'
  },
  {
    id: 25,
    category: 'Vegetables',
    product: 'Corn',
    wholesaleSource: '30 each · Kalfresh',
    wholesaleUnit: 'each',
    wholesalePrice: 67,
    wholesaleQty: 30,
    retailProduct: 'Corn',
    retailUnit: 'each',
    retailPrice: 3.5,
    avgWeightG: 300,
    confidence: 'ok',
    note: 'Retail also 3-for-$10 (~$3.33 ea) — using single-unit price.'
  },
  {
    id: 26,
    category: 'Vegetables',
    product: 'Cucumber (Lebanese)',
    wholesaleSource: '10kg box · Sunup',
    wholesaleUnit: 'kg',
    wholesalePrice: 82,
    wholesaleQty: 10,
    retailProduct: 'Cucumber',
    retailUnit: 'kg',
    retailPrice: 11.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 27,
    category: 'Vegetables',
    product: 'Eggplant',
    wholesaleSource: '5kg box · Barlow',
    wholesaleUnit: 'kg',
    wholesalePrice: 30,
    wholesaleQty: 5,
    retailProduct: 'Eggplant',
    retailUnit: 'kg',
    retailPrice: 9.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 28,
    category: 'Vegetables',
    product: 'Garlic',
    wholesaleSource: 'per kg · Bellbird',
    wholesaleUnit: 'kg',
    wholesalePrice: 60,
    wholesaleQty: 1,
    retailProduct: 'Garlic',
    retailUnit: 'kg',
    retailPrice: 79.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 29,
    category: 'Vegetables',
    product: 'Ginger',
    wholesaleSource: 'per kg · Nicholson/Lakeland',
    wholesaleUnit: 'kg',
    wholesalePrice: 21,
    wholesaleQty: 1,
    retailProduct: 'Ginger',
    retailUnit: 'kg',
    retailPrice: 29.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 30,
    category: 'Vegetables',
    product: 'Leek',
    wholesaleSource: '1 each (single) · Fordsdale',
    wholesaleUnit: 'each',
    wholesalePrice: 2.4,
    wholesaleQty: 1,
    retailProduct: 'Leeks',
    retailUnit: 'each',
    retailPrice: 3.9,
    avgWeightG: 150,
    confidence: 'ok',
    note: 'Retail also 3-for-$11 (~$3.67 ea) — using single-unit price.'
  },
  {
    id: 31,
    category: 'Vegetables',
    product: 'Mushrooms (Swiss Brown)',
    wholesaleSource: '2kg box · Bulla Park',
    wholesaleUnit: 'kg',
    wholesalePrice: 59,
    wholesaleQty: 2,
    retailProduct: 'Mushrooms loose',
    retailUnit: 'kg',
    retailPrice: 39.9,
    avgWeightG: null,
    confidence: 'ok',
    note: "Retail 'loose' may be a mixed variety, not exclusively Swiss Brown."
  },
  {
    id: 32,
    category: 'Vegetables',
    product: 'Pumpkin (Butternut)',
    wholesaleSource: 'per kg · Kalfresh',
    wholesaleUnit: 'kg',
    wholesalePrice: 2.6,
    wholesaleQty: 1,
    retailProduct: 'Pumpkin Butternut, whole',
    retailUnit: 'kg',
    retailPrice: 2.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 33,
    category: 'Vegetables',
    product: 'Pumpkin (Jap)',
    wholesaleSource: 'per kg · Sutton/Organic Ag/Barlow',
    wholesaleUnit: 'kg',
    wholesalePrice: 1.8,
    wholesaleQty: 1,
    retailProduct: 'Pumpkin Jap, whole',
    retailUnit: 'kg',
    retailPrice: 6.5,
    avgWeightG: null,
    confidence: 'verify',
    note: "Retail 'whole' is unusually far above both the retail 'cut' price ($2.50/kg) and wholesale — double-check this figure on the board."
  },
  {
    id: 34,
    category: 'Vegetables',
    product: 'Spinach (baby)',
    wholesaleSource: '1.5kg bulk bag · Coolibah Herbs',
    wholesaleUnit: 'kg',
    wholesalePrice: 29,
    wholesaleQty: 1.5,
    retailProduct: 'Spinach baby, loose',
    retailUnit: 'kg',
    retailPrice: 5.9,
    avgWeightG: null,
    confidence: 'verify',
    note: 'Wholesale line may be washed salad-grade baby spinach, a different product tier to commodity loose spinach — may not be a fair match.'
  },
  {
    id: 35,
    category: 'Vegetables',
    product: 'Squash',
    wholesaleSource: '4kg box · Moorland',
    wholesaleUnit: 'kg',
    wholesalePrice: 40,
    wholesaleQty: 4,
    retailProduct: 'Squash',
    retailUnit: 'kg',
    retailPrice: 5.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 36,
    category: 'Vegetables',
    product: 'Thyme',
    wholesaleSource: '1 bunch · Coolibah Herbs',
    wholesaleUnit: 'each',
    wholesalePrice: 3.5,
    wholesaleQty: 1,
    retailProduct: 'Thyme',
    retailUnit: 'kg',
    retailPrice: 19.9,
    avgWeightG: 30,
    confidence: 'verify',
    note: 'Bunch-to-kg conversion is very sensitive to the assumed bunch weight — replace 30g with a real weighed bunch if this matters to you.'
  },
  {
    id: 37,
    category: 'Vegetables',
    product: 'Tomato (cherry, punnet)',
    wholesaleSource: '1x200g punnet · Spring Lakes',
    wholesaleUnit: 'each',
    wholesalePrice: 3.3,
    wholesaleQty: 1,
    retailProduct: 'Tomatoes cherry, punnet',
    retailUnit: 'each',
    retailPrice: 7.9,
    avgWeightG: 200,
    confidence: 'ok',
    note: "Retail punnet weight isn't stated — assumed to match the wholesale 200g punnet."
  },
  {
    id: 38,
    category: 'Vegetables',
    product: 'Tomato (Roma)',
    wholesaleSource: '10kg box · Moorland',
    wholesaleUnit: 'kg',
    wholesalePrice: 54,
    wholesaleQty: 10,
    retailProduct: 'Tomatoes Roma, loose',
    retailUnit: 'kg',
    retailPrice: 7.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  },
  {
    id: 39,
    category: 'Vegetables',
    product: 'Turmeric',
    wholesaleSource: 'per kg · Bellbird/Nicholson',
    wholesaleUnit: 'kg',
    wholesalePrice: 23,
    wholesaleQty: 1,
    retailProduct: 'Turmeric',
    retailUnit: 'kg',
    retailPrice: 16.9,
    avgWeightG: null,
    confidence: 'verify',
    note: 'This figure was hard to read on the photo — double-check, it may be a different value.'
  },
  {
    id: 40,
    category: 'Vegetables',
    product: 'Peas (sugar snap)',
    wholesaleSource: '1kg · Beauvista',
    wholesaleUnit: 'kg',
    wholesalePrice: 29,
    wholesaleQty: 1,
    retailProduct: 'Peas sugar snap',
    retailUnit: 'kg',
    retailPrice: 3.5,
    avgWeightG: null,
    confidence: 'verify',
    note: 'Implausibly low next to a $29/kg wholesale cost — very likely a misread digit (perhaps $13.50-$23.50). Treat as unreliable until verified.'
  },
  {
    id: 41,
    category: 'Vegetables',
    product: 'Zucchini',
    wholesaleSource: '10kg box · Barlow/Isis River',
    wholesaleUnit: 'kg',
    wholesalePrice: 49,
    wholesaleQty: 10,
    retailProduct: 'Zucchini green',
    retailUnit: 'kg',
    retailPrice: 11.9,
    avgWeightG: null,
    confidence: 'ok',
    note: ''
  }
];

/** Wholesale lines with no corresponding price on the retail board — reference only, not part of the margin calculator. */
export const UNMATCHED_WHOLESALE: Record<string, string[]> = {
  'Fruit (other varieties)': [
    'Apples — Fuji, Gala, Granny Smith, Red Delicious, Southern Bliss, juicing grades',
    'Bananas — Cavendish, Lady Finger, Smoothie grade',
    'Quince',
    'Sapote (Black)'
  ],
  Vegetables: [
    'Artichoke (Jerusalem)',
    'Asian greens — bok choy, pak choy',
    'Beans — hand & machine picked',
    'Capsicum — coloured, snacking mix',
    'Carrot — bunch, yellow, 2nds, juicing grades',
    'Daikon',
    'Eschallot',
    'Garlic — Italian purple',
    'Lettuce — cos, iceberg, butter, oak, radicchio (box formats)',
    'Onion — brown & red, multiple sizes',
    'Parsnip',
    'Peas — snow',
    'Potato — Sebago, Dutch Cream, Kestral, Kipfler (all box formats)',
    'Radish',
    'Silverbeet / chard',
    'Sweet potato — gold, red'
  ],
  'Salads, kale & sprouts': [
    'Kale — green, black',
    'English spinach (bunch)',
    'Salad/rocket/superfood mix — bulk & punnet',
    'Sprouts & microgreens — broccoli, radish, snow pea, sunflower, wheatgrass, mixed varieties'
  ],
  'Herbs (bunch/sleeve/punnet)': [
    'Bay leaves',
    'Coriander',
    'Kaffir lime leaves',
    'Mint',
    'Parsley — curly & flat',
    'Rosemary'
  ],
  'Dates & eggs': ['Medjool dates — 5kg & 1kg formats', 'Organic eggs — 15 doz box']
};

export const DEFAULT_FREIGHT = { costPerTrip: 150, kgPerTrip: 300 };
